import { Button } from 'antd'
import {useState} from "react";
import type { NextPage } from 'next'
import { startRegistration } from "@simplewebauthn/browser"
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import useSWR from 'swr'

// @ts-ignore
const fetcher = (...args) => fetch(...args).then((res) => res.json())

const Home: NextPage = () => {
  // const { data, error } = useSWR('/api/start-registration', fetcher)

  const [loading, setLoading] = useState(false)
  const [option, setOption] = useState(null)

  const handleStart = () => {
    setLoading(true);
    fetch('api/auth/start-registration')
      .then((res) => res.json())
      .then((data) => {
        console.log(data)
        // setData(data)
        setLoading(false)
        // setOption(data);
        startRegistration(data)
          .then((attRes) => {
            fetch('api/auth/register', {
              method: "POST",
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify(attRes),
            })
              .then((res) => res.json())
              .then((result) => {
                console.log(result)
              })
          })
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={() => handleStart()}>Start</Button>

    </div>
  )
}

export default Home
